name: Deploy to Azure Container Apps

on:
  workflow_call:
    inputs:
      acr_username:
        description: 'Username do ACR'
        required: true
        type: string
      acr_password:
        description: 'Password do ACR'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS}}

      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          containerAppName: ${{ github.event.repository.name }}
          resourceGroup: ${{ vars.AZ_RESOURCE_GROUP }}
          imageToDeploy: ${{ vars.AZ_ACR_NAME }}.azurecr.io/${{ github.event.repository.name }}:${{ github.sha }}
          containerAppEnvironment: ${{ vars.AZ_ENV_NAME }}
          location: ${{ vars.AZ_LOCATION }}
          targetPort: ${{ vars.TARGET_PORT }}
          ingress: 'external'
          acrName: ${{ vars.AZ_ACR_NAME }}
          acrUsername: ${{ inputs.acr_username }}
          acrPassword: ${{ inputs.acr_password }}