name: Deploy to Azure Container Apps

on:
  workflow_call:
  
env:
  ARTIFACT_NAME: "app-jar"
  RESOURCE_GROUP: "azure-for-github-actions"
  ACR_NAME: "ghactions"
  CONTAINER_APP_NAME: "ghactions-ca"
  IMAGE_NAME: "demo-api"
  ENV_NAME: "ghactions-env"
  LOCATION: "eastus2"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout infra repo
        uses: actions/checkout@v4
        with:
          repository: maven-workflows/reusable-workflows
          path: infra-lib

      - name: Download JAR Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ./app-jar

      - name: Deploy to Azure Container Apps
        uses: maven-workflows/actions/actions/deploy-container-app@main
        with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          acr_name: ${{ env.ACR_NAME }}     
          image_name: ${{ env.IMAGE_NAME }}
          container_app_name: ${{ env.CONTAINER_APP_NAME }}
          resource_group: ${{ env.RESOURCE_GROUP }}
          environment_name: ${{ env.ENV_NAME }}
          location: ${{ env.LOCATION }}
