name: Deploy to Azure Container Apps

on:
  workflow_call:
    inputs:
      target_port:
        description: 'Porta que o container expõe'
        required: false
        type: string
        default: '8080'
    secrets:
      AZURE_CREDENTIALS:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Container Apps
        uses: maven-workflows/actions/.github/actions/deploy-container-app@main
        with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          acr_name: ${{ vars.AZ_ACR_NAME }}
          container_app_name: ${{ github.event.repository.name }}
          resource_group: ${{ vars.AZ_RESOURCE_GROUP }}
          environment_name: ${{ vars.AZ_ENV_NAME }}
          location: ${{ vars.AZ_LOCATION }}
          image_name: ${{ github.event.repository.name }}
          target_port: ${{ inputs.target_port }}