name: Deploy to Azure Container Apps

on:
  workflow_call:
    inputs:
      target_port:
        description: 'Porta que o container expõe'
        required: false
        type: string
        default: '8080'
      acr_username:
        description: 'Username do ACR'
        required: true
        type: string
      acr_password:
        description: 'Password do ACR'
        required: true
        type: string
    secrets:
      AZURE_CREDENTIALS:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Azure CLI extension
        uses: azure/cli@v2
        with:
          inlineScript: |
            az extension add --name containerapp --upgrade

      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          appName: ${{ github.event.repository.name }}
          resourceGroup: ${{ vars.AZ_RESOURCE_GROUP }}
          imageToDeploy: ${{ vars.AZ_ACR_NAME }}.azurecr.io/${{ github.event.repository.name }}:${{ github.sha }}
          containerAppEnvironment: ${{ vars.AZ_ENV_NAME }}
          location: ${{ vars.AZ_LOCATION }}
          targetPort: ${{ inputs.target_port }}
          ingress: 'external'
          registryUrl: ${{ vars.AZ_ACR_NAME }}.azurecr.io
          registryUsername: ${{ inputs.acr_username }}
          registryPassword: ${{ inputs.acr_password }}