name: Deploy to Azure Container Apps

# Este workflow pode ser chamado por outro workflow (workflow_call)
on:
  workflow_call:
    secrets:
      AZURE_CREDENTIALS:
        description: 'JSON do Service Principal para fazer login no Azure'
        required: true

env:
  ARTIFACT_NAME: "app-jar"                     # Nome do artifact que contém o JAR
  RESOURCE_GROUP: "azure-for-github-actions"   # Resource Group onde residem os recursos
  ACR_NAME: "ghactions"                        # Nome do Azure Container Registry (sem o .azurecr.io)
  CONTAINER_APP_NAME: "ghactions-ca"           # Nome do Container App (será criado/atualizado)
  IMAGE_NAME: "demo-api"                       # Nome lógico da imagem (prefixo antes da tag)
  ENV_NAME: "ghactions-env"                    # Nome do Container Apps Environment (será criado/atualizado)
  LOCATION: "eastus2"                          # Região onde os recursos residem

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # ------------------------------------------------------
      # 1) Baixar o JAR que foi publicado como artifact no build
      # ------------------------------------------------------
      - name: Download JAR Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ./app-jar

      # ------------------------------------------------------
      # 2) Login no Azure com Service Principal
      # ------------------------------------------------------
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # ------------------------------------------------------
      # 3) Criar Dockerfile dinamicamente, copiando o JAR para dentro da imagem
      # ------------------------------------------------------
      - name: Create Dockerfile
        run: |
          cat << 'EOF' > Dockerfile
          FROM openjdk:11-jre-slim
          COPY app-jar/*.jar /app.jar
          WORKDIR /
          EXPOSE 8080
          ENTRYPOINT ["java", "-jar", "/app.jar"]
          EOF

      # ------------------------------------------------------
      # 4) Build & Push da imagem Docker para o ACR
      # ------------------------------------------------------
      - name: Build and Push Docker Image
        run: |
          # Define a tag baseada no SHA do commit
          IMAGE_TAG="${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}"
          echo "Building image $IMAGE_TAG"
          docker build -f Dockerfile -t "$IMAGE_TAG" .

          # Autentica no ACR e faz push
          echo "Logging in to ACR ${{ env.ACR_NAME }}"
          az acr login --name "${{ env.ACR_NAME }}"
          echo "Pushing image to ACR"
          docker push "$IMAGE_TAG"

      # ------------------------------------------------------
      # 5) Garantir que a extensão Container Apps do Azure CLI esteja instalada
      # ------------------------------------------------------
      - name: Install Azure Container Apps Extension
        run: |
          if ! az extension show --name containerapp &> /dev/null; then
            az extension add --name containerapp
          fi

      # ------------------------------------------------------
      # 6) Criar ou Atualizar o Container App com 'az containerapp up'
      #    - Se não existir, criará:  
      #       • Log Analytics Workspace  
      #       • Environment do Container Apps  
      #       • O próprio Container App  
      #    - Se já existir, fará update da imagem  
      # ------------------------------------------------------
      - name: Deploy (az containerapp up)
        run: |
          IMAGE_TAG="${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}"

          az containerapp up \
            --name "${{ env.CONTAINER_APP_NAME }}" \
            --resource-group "${{ env.RESOURCE_GROUP }}" \
            --environment "${{ env.ENV_NAME }}" \
            --image "$IMAGE_TAG" \
            --location "${{ env.LOCATION }}" \
            --ingress external \
            --target-port 8080 \
            --registry-server "${{ env.ACR_NAME }}.azurecr.io"

