name: Publish Maven Package in Github Packages

on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Set up Java and Maven
        uses: actions/setup-java@v4
        with:
          java-version: ${{ vars.JAVA_VERSION }}
          distribution: 'temurin'

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: ./jar-artifact-directory

      - name: Generate Dynamic Version
        id: version
        run: |
          VERSION="1.${GITHUB_RUN_NUMBER}.${GITHUB_RUN_ATTEMPT}"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "Generated version: ${VERSION}"

      - name: Publish package to GitHub Packages
        run: |
          jarFile=$(find ./jar-artifact-directory -name "*.jar")
          
          ARTIFACT_ID="${GITHUB_REPOSITORY##*/}"

          GROUP_ID="${GITHUB_REPOSITORY_OWNER,,}"
          
          mvn --batch-mode deploy:deploy-file \
            -Dfile="$jarFile" \
            -DgroupId="$GROUP_ID" \
            -DartifactId="$ARTIFACT_ID" \
            -Dversion="${{ steps.version.outputs.version }}" \
            -Dpackaging="jar" \
            -DrepositoryId="github" \
            -Durl="https://maven.pkg.github.com/${{ github.repository }}" \
            -Dmaven.deploy.skip-duplicate=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}