# Workflow Name (English)
name: Publish Maven Package from Artifacts

on:
  workflow_call:

jobs:
  publish-package:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Set up Java and Maven
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: ./jar-artifact-directory

      - name: Download POM artifact
        uses: actions/download-artifact@v4
        with:
          name: app-pom
          path: ./pom-artifact-directory 

      - name: Publish package to GitHub Packages
        run: |
          mvn --batch-mode deploy:deploy-file \
            -Dfile="./jar-artifact-directory/${{ inputs.jar-path-in-artifact }}" \
            -DpomFile="./pom-artifact-directory/pom.xml" \
            -DrepositoryId="github" \
            -Durl="https://maven.pkg.github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}