name: Maven Build, Test & Sonar Reusable Workflow

on:
  workflow_call:
    inputs:
      run-tests:
        description: 'Run Maven tests?'
        required: true
        type: boolean
        default: true
      run-sonar-analysis:
        description: 'Execute Sonar analysis?'
        required: true
        type: boolean
        default: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ vars.JAVA_VERSION }}
          cache: 'maven'

      - name: Cache Maven Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Maven Build
        run: mvn -B clean package -DskipTests

      - name: Maven Test
        if: ${{ inputs.run-tests }}
        run: mvn test

      - name: Cache Sonar Scanner
        if: ${{ inputs.run-sonar-analysis }}
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: sonar-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}

      - name: SonarCloud Scan
        if: ${{ inputs.run-sonar-analysis }}
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.projectKey=${GITHUB_REPOSITORY##*/}
            -Dsonar.sources=src/main/java
            -Dsonar.tests=src/test/java
            -Dsonar.java.binaries=target/classes
            -Dsonar.java.test.binaries=target/test-classes
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
            -Dsonar.qualitygate.wait=true

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          retention-days: 3
          path: target/*.jar
          if-no-files-found: warn