name: Maven Build, Test & Sonar Reusable Workflow

on:
  workflow_call:
    inputs:
      run-tests:
        description: 'Run Maven tests?'
        required: true
        type: boolean
        default: true
      run-sonar-analysis:
        description: 'Execute Sonar analysis?'
        required: true
        type: boolean
        default: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ vars.JAVA_VERSION }}
          cache: 'maven'

      - name: Cache Maven Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Maven Build
        run: mvn -B clean package -DskipTests

      - name: Maven Test
        if: ${{ inputs.run-tests }}
        run: mvn test

      - name: Cache Sonar Scanner
        if: ${{ inputs.run-sonar-analysis }}
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: sonar-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}

      - name: Analyze with SonarCloud
        if: ${{ inputs.run-sonar-analysis }}
        run: |
          project_key="${GITHUB_REPOSITORY##*/}"
          mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=$project_key \
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}
            -Dsonar.qualitygate.wait=true

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          retention-days: 3
          path: target/*.jar
          if-no-files-found: warn