name: Build & Push Image

on:
  workflow_call:
    outputs:
      acr_username:
        description: "Username do ACR"
        value: ${{ fromJSON(toJSON(jobs.docker-build.outputs)).acr_username }}
      acr_password:
        description: "Password do ACR"
        value: ${{ fromJSON(toJSON(jobs.docker-build.outputs)).acr_password }}

jobs:
  docker-build:
    runs-on: ubuntu-latest

    outputs:
      acr_username: ${{ steps.acr_creds.outputs.ACR_USERNAME }}
      acr_password: ${{ steps.acr_creds.outputs.ACR_PASSWORD }}

    steps:
      - name: Download JAR Artifact
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: ./app-jar

      - name: Create Dockerfile
        run: |
          cat << EOF > Dockerfile
          FROM eclipse-temurin:21-jre
          COPY app-jar/*.jar /app.jar
          WORKDIR /
          EXPOSE ${{ vars.TARGET_PORT }}
          ENTRYPOINT ["java", "-jar", "/app.jar"]
          EOF

       # ───> ETAPA NOVA: Buildar a imagem localmente para TESTE <───
      - name: Build local para teste
        run: |
          docker build -t maven-class-lib:test .

      # ───> ETAPA QUE RODA A IMAGEM “test” E EXIBE STACK‐TRACE <───
      - name: Executar container localmente e exibir stack-trace
        run: |
          set -o pipefail
          # Mesmo que o java retorne exit code != 0, queremos ver o stack-trace no log e seguir adiante
          docker run --rm maven-class-lib:test || true
      - name: Listar conteúdo do JAR e inspecionar manifest
        run: |
          # Supondo que exista apenas um JAR em app-jar:
          JARFILE=$(ls app-jar/*.jar)
          echo "== Conteúdo do JAR =="
          jar tf "$JARFILE" | head -20
          echo "== MANIFEST.MF completo =="
          jar xf "$JARFILE" META-INF/MANIFEST.MF
          sed -n '1,20p' META-INF/MANIFEST.MF

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS}}
  
      - name: Get ACR Credentials
        id: acr_creds
        run: |
          ACR_USERNAME=$(az acr credential show --name "${{ vars.AZ_ACR_NAME }}" --query "username" -o tsv)
          ACR_PASSWORD=$(az acr credential show --name "${{ vars.AZ_ACR_NAME }}" --query "passwords[0].value" -o tsv)
          echo "ACR_USERNAME=$ACR_USERNAME" >> $GITHUB_OUTPUT
          echo "ACR_PASSWORD=$ACR_PASSWORD" >> $GITHUB_OUTPUT
        shell: bash

      - name: Login no Azure Container Registry
        uses: azure/docker-login@v2
        with:
          login-server: ${{ vars.AZ_ACR_NAME }}.azurecr.io
          username: ${{ steps.acr_creds.outputs.acr_username }}
          password: ${{ steps.acr_creds.outputs.acr_password }}

      - name: Build & Push Docker Image
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ vars.AZ_ACR_NAME }}.azurecr.io/${{ github.event.repository.name }}:${{ github.sha }}