name: Build & Push Image

on:
  workflow_call:

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Download JAR Artifact
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: ./app-jar

      - name: Create Dockerfile
        run: |
          cat << EOF > Dockerfile
          FROM eclipse-temurin:21-jre
          COPY app-jar/*.jar /app.jar
          WORKDIR /
          EXPOSE ${{ vars.TARGET_PORT }}
          ENTRYPOINT ["java", "-jar", "/app.jar"]
          EOF

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS}}
  
      - name: Login no Azure Container Registry
        uses: azure/docker-login@v2
        with:
          login-server: ${{ vars.AZ_ACR_NAME }}.azurecr.io
          username: ${{ secrets.AZ_USERNAME }}
          password: ${{ secrets.AZ_PASSWORD }}

      - name: Build & Push Docker Image
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ vars.AZ_ACR_NAME }}.azurecr.io/${{ github.event.repository.name }}:latest